version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: order_db
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP 连接端口
      - "15672:15672"   # 管理控制台

  order_server:
    build: .
    depends_on:
      - mysql
      - redis
      - rabbitmq
    environment:
      ORDER_SERVER_CONFIG: /opt/order_server/config/order_server.yaml
    ports:
      - "8080:8080"
